### ISSUE TITLE
有没有遇到ts文件合并后，视频播放没有声音的情况？

### ISSUE THREAD

**Issue by CocoaML** [Greyh4t/m3u8-Downloader#2]
有没有遇到ts文件合并后，视频播放没有声音的情况？

**Comment by Greyh4t** [comment]
> 有没有遇到ts文件合并后，视频播放没有声音的情况？

没有呢，方便发链接出来吗

**Comment by CocoaML** [comment]
> > 有没有遇到ts文件合并后，视频播放没有声音的情况？
> 
> 没有呢，方便发链接出来吗

嗯嗯，是我代码的问题，谢谢您
