### ISSUE TITLE
 os.remove(os.path.join(self.dir, file_name))  fail  on win32

### ISSUE THREAD

**Issue by tablecell** [Greyh4t/m3u8-Downloader#4]
Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenle
t.run
  File "m3u8.py", line 86, in _join_file
    os.remove(os.path.join(self.dir, file_name))
WindowsError: [Error 32] : 'video\\Bbi7W6T7.ts'
2020-06-22T23:54:26Z <Greenlet at 0x2a72250: <bound method Downloader._join_file
 of <__main__.Downloader instance at 0x027F7DC8>>> failed with WindowsError

**Comment by Greyh4t** [comment]
"[Error 32]" means that the file is being used by another process, did you open the file by video player while it was downloading

**Comment by tablecell** [comment]
> 
> 
> "[Error 32]" means that the file is being used by another process, did you open the file by video player while it was downloading

you are right   ,  play ts file  until   all downloaded
